Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
src += Glob('*.cpp')
src += Glob('*.lib')
CPPPATH = [cwd, ]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
